### ISSUE TITLE
1.8.12 IDE : errors while trying to verify any program (Vista 32 business & XPsp3 pro)

### ISSUE THREAD

**Issue by VincentPrunier** [iseries1/BWiFi#2]
Hi,
I've just installed the newest ide (title) to reboot old projects and activities (last uses with 1.0.3 a while ago)... So firstly installed:
-On a NEC laptop, vista sp2 business 32, jdk8u241, Uno board (but isn't a cause): installation, board driver, communication with board all OK...
-BUT as soon as I try any program verifying, messages below appear (pointing the first line in program, which is... a comment! Anyway, any programs do the same "before any real program verifying"...)
--------------Messages start-----------------------------
---------------------------------------------------------------------
processing.app.debug.RunnerException
	at cc.arduino.Compiler.callArduinoBuilder(Compiler.java:317)
	at cc.arduino.Compiler.loadPreferences(Compiler.java:216)
	at cc.arduino.Compiler.build(Compiler.java:175)
	at processing.app.SketchController.build(SketchController.java:664)
	at processing.app.Editor$BuildHandler.run(Editor.java:1624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "C:\Program Files\Arduino\arduino-builder": CreateProcess error=193, %1 n'est pas une application Win32 valide
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
	at cc.arduino.Compiler.callArduinoBuilder(Compiler.java:297)
	... 5 more
Caused by: java.io.IOException: CreateProcess error=193, %1 n'est pas une application Win32 valide
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 7 more
--------------Messages end-----------------------------
---------------------------------------------------------------------
-Tried to "run" straight that "arduino-builder.exe" just to see: same win kind of message "... isn't a valid win32 app" (OK, I suppose it isn't intended to be run like that... Just to see...)
-Tried to uninstall JDK to have only JRE, uninstall/reinstall IDE... The same!

-Then I tried on my XPsp3 pro 32 desktop, JRE8u71... All the same!

I'm just desperate... Missed anything? I've seen nothing in forum about that (sorry if I'm wrong...).

Thanking you forwardly for helping me on that!
Regards,
Vincent

**Comment by VincentPrunier** [comment]
... Sorry, I don't understand why it has been included in you rep'...
Regards,
vp
